In [7]:
import pandas as pd
import numpy as np
import os
import glob
from numpy import *

In [8]:
v = np.array([1,2,3])
v.shape

(3,)

In [9]:
# make a column matrix of the vector v
v[:, newaxis]

array([[1],
       [2],
       [3]])

In [12]:
# column matrix
v[:,newaxis].shape

(3, 1)

In [13]:
# row matrix
v[newaxis,:].shape

(1, 3)

In [10]:
A = np.array([[n+m*10 for n in range(5)] for m in range(5)])
# a block from the original array
x = A[1:4, 1:4]

# strides
y = A[::2, ::2]

In [11]:
x,y

(array([[11, 12, 13],
        [21, 22, 23],
        [31, 32, 33]]),
 array([[ 0,  2,  4],
        [20, 22, 24],
        [40, 42, 44]]))