In [1]:
import pandas as pd
import numpy as np
import os
import glob
import matplotlib.pyplot as plt

In [25]:
A = np.array([1,2,3,4,5])
out = A[::] # lower, upper, step all take the default values
out = A[::2] # step is 2, lower and upper defaults to the beginning and end of the 
out = A[:3] # first three elements
out = A[3:] # elements from index 3
out = A[-1] # the last element in the array
out = A[-3:] # the last three elements

In [27]:
A = np.array([[n+m*10 for n in range(5)] for m in range(5)])
# a block from the original array
out = A[1:4, 1:4]
# strides
out = A[::2, ::2]


In [2]:
# indexing elements from multidimensional arrays
A = np.array([x**2 for x in range(1, 11)]).reshape(2, 5)

print(A, end='\n\n')
print('A[0]\t\t', A[0])
print('A[-1]\t\t', A[-1])
print('A[0][0]\t\t', A[0][0])
print('A[-1][-1]\t', A[-1][-1])
#print('', A[])

[[  1   4   9  16  25]
 [ 36  49  64  81 100]]

A[0]		 [ 1  4  9 16 25]
A[-1]		 [ 36  49  64  81 100]
A[0][0]		 1
A[-1][-1]	 100


In [3]:
# slicing NumPy arrays
cubes = np.arange(1, 13).reshape(4, 3)**3 # cubes of 1-12

print(cubes[:,:], end='\n\n')         # all rows, all cols
print('First Column:\t', cubes[:, 0]) # first col
print('Last Column:\t', cubes[:, -1]) # last col
print('First Row:\t', cubes[0, :])    # first row
print('Last Row:\t', cubes[-1, :])    # last row

[[   1    8   27]
 [  64  125  216]
 [ 343  512  729]
 [1000 1331 1728]]

First Column:	 [   1   64  343 1000]
Last Column:	 [  27  216  729 1728]
First Row:	 [ 1  8 27]
Last Row:	 [1000 1331 1728]


In [4]:
# iterating through array elements
A = np.array([x+1 for x in range(10)])
A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
for a in A:
    print(a, end=',')

1,2,3,4,5,6,7,8,9,10,

In [6]:
A = A.reshape(2, 5)

for a in A[0,:]: # for element in row 1
    print(a**2, end=',')

1,4,9,16,25,

In [7]:
# Advanced: using ... for axis completion
A = np.arange(125).reshape(5, 5, 5) + 1

print('A[0, ...] == A[0, :, :]', end='\n\n')
print(A[0, ...], '\n\n', A[0, :, :])

A[0, ...] == A[0, :, :]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]] 

 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [8]:
# flattening a 5x5x5 array for iteration
for a in A.flat:
    print(a, end=',')

1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,

#### Changing the shape of an array

In [9]:
a = np.floor(10*np.random.random((3, 4)))
print(a)
print(a.shape)

[[7. 1. 6. 0.]
 [2. 9. 9. 9.]
 [6. 8. 7. 7.]]
(3, 4)


In [10]:
a.reshape(6, 2) # returns a COPY of the array reshaped


array([[7., 1.],
       [6., 0.],
       [2., 9.],
       [9., 9.],
       [6., 8.],
       [7., 7.]])

In [11]:
a.T # returns a COPY of the array, transposed

array([[7., 2., 6.],
       [1., 9., 8.],
       [6., 9., 7.],
       [0., 9., 7.]])

In [12]:
print('A:\t', a.shape)
print('A^T:\t', a.T.shape)

A:	 (3, 4)
A^T:	 (4, 3)


In [13]:
A = np.floor(10*np.random.random((3, 4)))

A.reshape(4, 3) # reshape returns a COPY of A
print(A, 'array A remains unchanged')

A.resize(4, 3) # resize modifies array A
print(A, 'array A is of a new shape')

[[0. 3. 7. 4.]
 [9. 3. 8. 5.]
 [0. 2. 4. 7.]] array A remains unchanged
[[0. 3. 7.]
 [4. 9. 3.]
 [8. 5. 0.]
 [2. 4. 7.]] array A is of a new shape


In [15]:
a = np.zeros(9, dtype=int).reshape(3, 3)
b = np.ones(9, dtype=int).reshape(3, 3)

# stack horizontally:
hor = np.hstack((a, b))
ver = np.vstack((a, b))

print('a:\n', a)
print('b:\n', b)
print('Horizontal Stack:\n', hor)
print('Vertical Stack:\n', ver)

a:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]
b:
 [[1 1 1]
 [1 1 1]
 [1 1 1]]
Horizontal Stack:
 [[0 0 0 1 1 1]
 [0 0 0 1 1 1]
 [0 0 0 1 1 1]]
Vertical Stack:
 [[0 0 0]
 [0 0 0]
 [0 0 0]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [16]:
# similarly, row_stack and column_stack can be used to stack into 2D arrays
r_stack = np.row_stack((a, b))
c_stack = np.column_stack((a, b))

print('Horizontal Stack:\n', hor)
print('Vertical Stack:\n', ver)
print('Column Stack:\n', c_stack)
print('Row Stack:\n', r_stack)

Horizontal Stack:
 [[0 0 0 1 1 1]
 [0 0 0 1 1 1]
 [0 0 0 1 1 1]]
Vertical Stack:
 [[0 0 0]
 [0 0 0]
 [0 0 0]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
Column Stack:
 [[0 0 0 1 1 1]
 [0 0 0 1 1 1]
 [0 0 0 1 1 1]]
Row Stack:
 [[0 0 0]
 [0 0 0]
 [0 0 0]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [17]:
from numpy import newaxis

r_stack = np.row_stack((a[newaxis], b[newaxis]))
c_stack = np.column_stack((a[newaxis], b[newaxis]))

print('Column Stack:\n', c_stack)
print('Row Stack:\n', r_stack)

Column Stack:
 [[[0 0 0]
  [0 0 0]
  [0 0 0]
  [1 1 1]
  [1 1 1]
  [1 1 1]]]
Row Stack:
 [[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [18]:
# use range literals to concatenate arrays on the fly
np.r_[1:5, 5, 6:10, 10]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
np.c_[1:5]

array([[1],
       [2],
       [3],
       [4]])

#### splitting large array into smaller ones

In [20]:
# use hsplit or vsplit to split arrays
a = np.ones(9).reshape(3, 3)

a_1, a_2, a_3 = np.hsplit(a, 3) # split a into 3 arrays

print(a, end='\n\n')
print(a_1, end='\n\n')
print(a_2, end='\n\n')
print(a_3, end='\n\n')

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

[[1.]
 [1.]
 [1.]]

[[1.]
 [1.]
 [1.]]

[[1.]
 [1.]
 [1.]]



##### view and copy

In [21]:
a = np.arange(15).reshape(5, 3)
b = a
a is b

True