In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
import glob

#### Creating arrays from Python's sequence types

In [2]:
squares = [x**2 for x in range(10)]         # python list
cubes = tuple(x**3 for x in range(10))      # python tuple
evens = {x for x in range(10) if x%2 == 0}  # python set

print(type(squares))
print(type(cubes))
print(type(evens))

<class 'list'>
<class 'tuple'>
<class 'set'>


In [3]:
a = np.array(squares)
b = np.array(cubes)
c = np.array(evens)

if type(a) == type(b) == type(c):
    print(type(a))

<class 'numpy.ndarray'>


In [4]:
seq2 = [[x, x**2, x**3] for x in range(10)]
seq3 = [[[x for x in range(3)], [y for y in range(3, 6)]] for z in range(10)]

a = np.array(seq2) # create array from nested lists of depth 2
b = np.array(seq3) # create array from nested lists of depth 3

print(a.ndim)
print(b.ndim)

2
3


In [6]:
odds = list(i for i in range(10) if i%2 != 0)

odds

[1, 3, 5, 7, 9]

In [7]:
zeros = np.zeros((3, 3), dtype=np.int32) # create a 3x3 array of 0's
ones = np.ones((2, 2), dtype=np.float64) # create a 2x2 array of 1's
empty = np.empty((3, 3))

print(zeros, zeros.dtype.name)
print(ones, ones.dtype.name)
print(empty, empty.dtype.name)

[[0 0 0]
 [0 0 0]
 [0 0 0]] int32
[[1. 1.]
 [1. 1.]] float64
[[4.63822327e-310 0.00000000e+000 6.94626334e-310]
 [6.94626335e-310 6.94626335e-310 6.94626335e-310]
 [6.94626335e-310 6.94626334e-310 1.26480805e-321]] float64


In [8]:
a = np.arange(5, 30, 5) # create array from range [5, 30) with step of 5
a

array([ 5, 10, 15, 20, 25])

In [9]:
b = np.linspace(0, 1, 100) # create array of 100 values between 0 and 1
b

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [10]:
dim1 = np.arange(15)                   # Create 1 1x15 matrix;  n=1
dim2 = np.arange(15).reshape(3, 5)     # Create 1 3x5 matrix;   n=2
dim3 = np.arange(24).reshape(2, 3, 4)  # Create 2 3x4 matrices; n=3

print(dim1, end='\t[1x15]\n\n')
print(dim2, end='\t[3x5]\n\n')
print(dim3, end='\t[2x3x4]')

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]	[1x15]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]	[3x5]

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]	[2x3x4]

In [11]:
very_large = np.arange(10000).reshape(100, 100)
print(very_large) # printing a very large array

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


#### Common NumPy array operations
- Arithmetic operators on arrays apply elementwise.
- A new array is created and filled with the result.

In [12]:
a = np.arange(10) 
b = np.array([2 for x in range(10)])
c = np.ones(10, dtype=int)
result = a + b - c # add 2 and subtract 1 from each element of a

print(result)

[ 1  2  3  4  5  6  7  8  9 10]


In [13]:
result **= 2 # square each element of result
result

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [14]:
result < 10

array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [15]:
a = np.ones(15).reshape(3, 5)
b = np.ones(15).reshape(5, 3)

mult = a * 10            # element-wise multiplication
dot_prod1 = a.dot(b)     # dot product version 1
dot_prod2 = np.dot(a, b) # dot product version 2

print(mult, end='\n\n')
print(dot_prod1, end='\n\n')
print(dot_prod2)

[[10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10.]]

[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]

[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]


In [16]:
a, b = dot_prod1, dot_prod2

a += b # += and *= act in place -- they modify the existing array
a

array([[10., 10., 10.],
       [10., 10., 10.],
       [10., 10., 10.]])

In [17]:
# array operations result in upcasting (result is more general type)
a = np.ones(10, dtype=int)
b = np.ones(10, dtype=float)
c = np.ones(10, dtype=complex)

a_plus_b = a + b # int + float
b_plus_c = b + c # float + complex

print(a_plus_b.dtype.name)
print(b_plus_c.dtype.name)

float64
complex128


In [18]:
# useful array methods
a = np.arange(1, 11)
print('Sum:', a.sum())
print('Min:', a.min())
print('Max:', a.max())

Sum: 55
Min: 1
Max: 10


In [19]:
# applying methods to a single axis
a = np.arange(15).reshape(3, 5) + 1

print(a.sum(axis=0)) # sum each column
print(a.min(axis=1)) # min of each row
a

[18 21 24 27 30]
[ 1  6 11]


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

#### Indexing slicing and iterating

In [20]:
# indexing elements from multidimensional arrays
A = np.array([x**2 for x in range(1, 11)]).reshape(2, 5)

print(A, end='\n\n')
print('A[0]\t\t', A[0])
print('A[-1]\t\t', A[-1])
print('A[0][0]\t\t', A[0][0])
print('A[-1][-1]\t', A[-1][-1])
#print('', A[])

[[  1   4   9  16  25]
 [ 36  49  64  81 100]]

A[0]		 [ 1  4  9 16 25]
A[-1]		 [ 36  49  64  81 100]
A[0][0]		 1
A[-1][-1]	 100
